---
- name: set up my macbook
  hosts: localhost
  connection: local
  become: False
  roles:
    - { role: homebrew-cask, tags: [ homebrew-cask ] }
    - { role: env, tags: [ env ] }
    - { role: mac, tags: [ mac ] }
