---
- homebrew_tap:
    name: homebrew/cask

- homebrew: name=cask state=latest

- homebrew_tap:
    name: "{{item}}"
  with_items: "{{homebrew_cask_repositories}}"
  when: homebrew_cask_repositories|bool

- name: install/upgrade Homebrew Cask packages
  homebrew_cask:
    name: "{{item.name | default(item)}}"
    state: "{{item.state | default('present')}}"
    install_options: 'appdir=/Applications'
  with_items: "{{homebrew_cask_packages}}"
  when: homebrew_cask_packages|bool
