---
AllCops:
  DisplayCopNames: yes
  TargetRubyVersion: 2.3
  Exclude:
    - "bin/*"
    - "db/schema.rb"

Metrics:
  Enabled: no

Rails:
  Enabled: no

Bundler/OrderedGems:
  Enabled: no

Lint/AmbiguousRegexpLiteral:
  Enabled: no

Lint/UnusedMethodArgument: # unreliable with keyword arguments
  Enabled: no

Lint/UselessAccessModifier:
  Enabled: no

Style/AccessorMethodName:
  Enabled: no

Style/Alias:
  Enabled: no

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/AsciiComments:
  Enabled: no

Style/BracesAroundHashParameters:
  Enabled: no

Style/ClassAndModuleChildren:
  Enabled: no

Style/ClassCheck:
  EnforcedStyle: kind_of?

Style/Documentation:
  Enabled: no

Style/DoubleNegation:
  Enabled: no

Style/EmptyElse:
  EnforcedStyle: empty

Style/FormatString:
  Enabled: no

Style/FrozenStringLiteralComment:
  Enabled: no

Style/GlobalVars:
  AllowedVariables:
    - '$redis'

Style/GuardClause:
  Enabled: no

Style/IndentHash:
  EnforcedStyle: consistent

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/NumericPredicate:
  Enabled: no

Style/PredicateName:
  Enabled: no

Style/PreferredHashMethods: # tries to use .has_key? for ActiveModel::Errors and other hash-like objects
  Enabled: no

Style/RedundantParentheses: # cause infinite correction loop in some cases.
  Enabled: no

Style/RegexpLiteral:
  Enabled: no

Style/SingleLineBlockParams:
  Enabled: no

Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: space

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: consistent_comma
