---
- name: restart Dock
  shell: |
    killall Dock

- name: restart Finder
  shell: |
    killall Finder

- name: restart SystemUIServer
  shell: |
    killall SystemUIServer

- name: restore iterm2 configuration
  shell: |
    plutil -convert binary1 -o "{{ ansible_user_dir }}/Library/Preferences/com.googlecode.iterm2.plist" ./com.googlecode.iterm2.plist
  args:
    chdir: roles/mac/files/Library/Preferences
