---
- name: check if iterm2 config is differ
  shell: |
    diff <(plutil -convert binary1 -o - ./com.googlecode.iterm2.plist | md5 -q) <(md5 -q ~/Library/Preferences/com.googlecode.iterm2.plist)
  args:
    chdir: roles/mac/files/Library/Preferences
    executable: /bin/bash
  register: diff_result
  check_mode: no
  failed_when: false
  changed_when: diff_result.rc != 0
  notify:
    - restore iterm2 configuration

- name: install iterm2 imgls
  get_url: url=https://raw.githubusercontent.com/gnachman/iTerm2/master/tests/imgls dest=/usr/local/bin/imgls mode=0755

- name: install iterm2 imgcat
  get_url: url=https://raw.githubusercontent.com/gnachman/iTerm2/master/tests/imgcat dest=/usr/local/bin/imgcat mode=0755

- name: setup OS X defaults
  osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - "{{ osx_defaults }}"

- name: setup OS X defaults which use array values and restart Finder, Dock and Menubar
  script: mac.sh

- name: install python
  shell: pyenv install "{{ item }}"
  args:
    executable: /bin/bash
  ignore_errors: yes
  with_items:
    - 2.7.14
    - 3.6.2

- name: set global python versions
  shell: pyenv global 2.7.14 3.6.2

- name: init rbenv
  shell: rbenv init
  ignore_errors: yes

- name: install ruby
  shell: rbenv install "{{ item }}"
  args:
    executable: /bin/bash
  ignore_errors: yes
  with_items:
    - 2.4.4
    - 2.5.1

- name: rehash
  shell: rbenv rehash

- name: set global ruby version 2.5.1
  shell: |
    rbenv global 2.5.1

- name: install gem
  gem:
    name: "{{item}}"
    state: latest
    executable: ~/.rbenv/shims/gem
  with_items:
    - bundler
    - rsense
    - rails
