---
- name: copy envs
  shell: |
    cp -f {{ item.file }} ~/{{ item.file }}
  args:
    chdir: roles/env/files
    executable: /bin/bash
  with_items:
    - "{{ env_files }}"

- name: clone git repositories
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    accept_hostkey: yes
  with_items:
    - "{{ git_repositories }}"

- name: install git-foresta
  get_url: url=https://github.com/takaaki-kasai/git-foresta/raw/master/git-foresta dest=~/bin/git-foresta mode=0755

- name: change login shell to fish
  become: yes
  become_method: sudo
  ignore_errors: yes
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/local/bin/fish
    state: present
