---
- name: make .nvm directory
  file: path=~/.nvm state=directory

- name: copy envs
  shell: |
    cp -f {{ item.file }} ~/{{ item.file }}
  args:
    chdir: roles/env/files
    executable: /bin/bash
  with_items:
    - "{{ env_files }}"

- name: clone git repositories
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    accept_hostkey: yes
  with_items:
    - "{{ git_repositories }}"

- name: change login shell to fish
  become: yes
  become_method: sudo
  ignore_errors: yes
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/local/bin/fish
    state: present
